export enum EProductsActions {
    PRODUCTS_PENDING = 'PRODUCTS_PENDING',
    PRODUCTS_FETCHED = 'PRODUCTS_FETCHED',
    PRODUCTS_CLEAR = 'PRODUCTS_CLEAR',
    PRODUCTS_ITEM_REMOVE = 'PRODUCTS_ITEM_REMOVE',
    PRODUCTS_ITEM_CHANGE_QUANTITY = 'PRODUCTS_ITEM_CHANGE_QUANTITY',
    PRODUCT_DELETE = 'PRODUCT_DELETE',
    PRODUCTS_REVERT = 'PRODUCTS_REVERT',
  }
