export enum ECartActions {
    CART_PENDING = 'CART_PENDING',
    CART_FETCHED = 'CART_FETCHED',
    CART_UPDATE = 'CART_UPDATE',
    CART_CLEAR = 'CART_CLEAR',
    CART_ITEM_REMOVE = 'CART_ITEM_REMOVE',
}
